export PRODIR = ../..

export THIRDPARTYDIR = E:/workspace/ThirdParty

BINDIR = ../bin/

OBJSDIR = ../objs/

OBJS =		

LIBS =

ALL_TARGET = all	VNA
CLEAN_TARGET = clean cleanVNA
	
.PHONY:		 $(ALL_TARGET) $(CLEAN_TARGET)

all:	VNA

VNA:	
	(cd ./VNA; make all)


clean:	cleanVNA

cleanVNA:
	(cd ./VNA; make clean)
	